### ISSUE TITLE
New items

### ISSUE THREAD

**Issue by QQtin3** [Crownicles/Crownicles#1955]
- [ ] Item de Bombafox, besoin d'une validation de @BastLast pour celui-ci histoire d'être sûr

**Comment by quenquentin** [comment]
![Screenshot_20230525_160456.jpg](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/56274541/d698f487-5fd5-4210-8fc0-d43dad6198b3)

**Comment by BastLast** [comment]
faudra voir pr léquilibrage, go mettre l'autre item donateur dans cette issue

**Comment by BastLast** [comment]
@quenquentin  on en est ou sur les items donateurs ?

**Comment by quenquentin** [comment]
Pas eu de nouvelles demande depuis, je remets un message sur discord

**Comment by quenquentin** [comment]
symsym
![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/56274541/152e1a3f-0708-4ed3-bc0a-9e354de576b0)

**Comment by quenquentin** [comment]
Aiko
![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/56274541/c6786de3-0fdd-4a24-9915-2e158d840ce9)

**Comment by quenquentin** [comment]
EasyGamer
![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/56274541/a5adc45f-60e2-436d-a8b5-80dfb6ddfde2)

**Comment by QQtin3** [comment]
Noza
https://cdn.discordapp.com/attachments/1071197918591197274/1173342754546401400/Screenshot_20231112_202208.jpg?ex=65639b98&is=65512698&hm=20b7fb9313f4638eb0679624c2d871f2998f780955652317d41a51358ccfb0f5&

**Comment by QQtin3** [comment]
Voisin + Ravenclaw
![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/56274541/927a0d85-9634-4cea-bdac-71286bb4b3b6)

**Comment by Aikoo-Sama** [comment]
> Voisin + Ravenclaw ![image](https://user-images.githubusercontent.com/56274541/282321116-927a0d85-9634-4cea-bdac-71286bb4b3b6.png)

Mon dieu mais att ils ajoutent tlm d'items ils ont débourser des millions dans db ou quoi ???

**Comment by Aikoo-Sama** [comment]
Donc en gros tous les items depuis la création de cette issue sont à ajouter ?

**Comment by Aikoo-Sama** [comment]
La Poudre de Squelette est vrmt une potion ? Ses stats correspondent plus à un item, après why not

**Comment by BastLast** [comment]
> > Voisin + Ravenclaw ![image](https://user-images.githubusercontent.com/56274541/282321116-927a0d85-9634-4cea-bdac-71286bb4b3b6.png)
> 
> Mon dieu mais att ils ajoutent tlm d'items ils ont débourser des millions dans db ou quoi ???

Normalement on autorise 1 item par don,  exceptionnellement on a fait une exception vu que c'était un don de 80 euros

**Comment by Aikoo-Sama** [comment]
> > > Voisin + Ravenclaw ![image](https://user-images.githubusercontent.com/56274541/282321116-927a0d85-9634-4cea-bdac-71286bb4b3b6.png)
> > 
> > 
> > Mon dieu mais att ils ajoutent tlm d'items ils ont débourser des millions dans db ou quoi ???
> 
> Normalement on autorise 1 item par don, exceptionnellement on a fait une exception vu que c'était un don de 80 euros

Ok ça marche

**Comment by Aikoo-Sama** [comment]
> * [ ]  Item de Bombafox, besoin d'une validation de @BastLast pour celui-ci histoire d'être sûr

@BastLast j'ai toujours besoin de ton avis pour ce giga chad qui me paraît très haut pour un leg, je l'aurais plus mis en mythique perso

**Comment by Aikoo-Sama** [comment]
**Liste des Potions :**

- [ ] Jus de Pomme de Terre - Commun - Temps + 15m
- [ ] Eau de mer commun aucun effet
- [ ] Poudre de squelette spéciale, attaque 116, défense 50, 
- [ ] Bave de troll épique, attaque plus 188 pendant le prochain combat, 
- [ ] Larme de titan légendaire, vie plus 170. 

**Liste des objets :**
- [ ] Le Script de Easy - Objet Vitesse Légendaire :cockroach: 
- [ ] Fusée en carton, spéciale, avance le temps de 45 minutes, 
- [ ] Trèfle à 4 feuilles, épique, défense plus 39 pendant les combats, 
- [ ] Roulo PQ, légendaire, attaque plus 3 pendant les combats, 
- [ ] Étoile du destin, mythique, défense plus 152 pendant les combats, 
- [ ] Guitare Électrique, rare, attaque plus 52 pendant les combats, 

**Liste des armures et boucliers :**
- [ ] Lampe magique, spéciale, attaque 10, défense 40, vitesse 9, 
- [ ] Chapeau magique, exotique, 27 d'attaque, 2 de défense, vitesse 10. 

**Liste des armes :**
- [ ] Épée du dragon légendaire, attaque 98, défense 115, vitesse 18, 
- [ ] Corne de licorne, rare, attaque 30, défense 62, 
- [ ] Baguette de fibonacci, mythique, attaque 169, défense 19, vitesse 19. 
- [ ] Le game over mythique, attaque 222. 
- [ ] Le Torchon du Cuisinier :fork_and_knife: Rare

**Comment by BastLast** [comment]
> > * [ ]  Item de Bombafox, besoin d'une validation de @BastLast pour celui-ci histoire d'être sûr
> 
> @BastLast j'ai toujours besoin de ton avis pour ce giga chad qui me paraît très haut pour un leg, je l'aurais plus mis en mythique perso

Je ferai un passage sur tout une fois que c'est implémenté

**Comment by Aikoo-Sama** [comment]
Valeurs à jours, légèrement équilibrées et implémentées : 

<img width="267" alt="image" src="https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/46852063/9cc4ea0b-9fd3-4761-a183-1000ff1e79be">
