### ISSUE TITLE
Typos pour la 4.4.3

### ISSUE THREAD

**Issue by symsym-1629** [Crownicles/Crownicles#2001]
Suite de la #1822

**Comment by romain22222** [comment]
![Screenshot_20230810_204438_Discord.jpg](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/29299679/499a608d-02c1-44f2-948c-8645af831c67)

Remplacer quelques heures par quelques minutes, n importe quel mini event a un écart d au mieux 10m et au pire 18s, donc ca n est pas logique que ca soit des heures

**Comment by leuhvraiminoryo** [comment]
bon, ça fait un moment qu'ça me dérange, et vu que symou semble faire la map en anglais actuellement, autant en profiter pour au moins corriger ça : 

L'étendue (le lieu) est traduite "the extent" en anglais, ce qui est une erreur de traduction.

Il faudrait utiliser "expanse" et pas "extent" : bien que les deux puissent vouloir dire "étendue" en français, nous sommes dans un cas où le sens est plus proche de "expanse" plutôt que de "extent" (extent étant l'étendue des possibilités, ou encore une façon de dire "jusqu'à quel point", parler de quantitatif quoi, alors que pour le cas d'une étendue, vaste zone d'un seul morceau, c'est expanse (sauf si c'est étendue + la chose dont c'est une étendue, auquel cas okay en anglais utiliser extent ira, comme dans "an extent of forest", même si expanse reste à privilégier imo))

donc faudrait changer ça aux quelques endroits où ça apparaît

**Comment by voltou91** [comment]
![image](https://github.com/DraftBot-A-Discord-Adventure/DraftBot/assets/62652451/6a9e604c-bca1-43e2-a4f4-2bc245c3d12e)
Changement de l'émoji 🗿 par 🦠.

**Comment by Nargacaura** [comment]
https://github.com/DraftBot-A-Discord-Adventure/DraftBot/blob/dd6f8e70414fe52a5bef21c2848ea52f06d687a5/resources/text/advices.json#L193
"En combattant des adversaire**s**"

**Comment by BastLast** [comment]
> bon, ça fait un moment qu'ça me dérange, et vu que symou semble faire la map en anglais actuellement, autant en profiter pour au moins corriger ça :
> 
> L'étendue (le lieu) est traduite "the extent" en anglais, ce qui est une erreur de traduction.
> 
> Il faudrait utiliser "expanse" et pas "extent" : bien que les deux puissent vouloir dire "étendue" en français, nous sommes dans un cas où le sens est plus proche de "expanse" plutôt que de "extent" (extent étant l'étendue des possibilités, ou encore une façon de dire "jusqu'à quel point", parler de quantitatif quoi, alors que pour le cas d'une étendue, vaste zone d'un seul morceau, c'est expanse (sauf si c'est étendue + la chose dont c'est une étendue, auquel cas okay en anglais utiliser extent ira, comme dans "an extent of forest", même si expanse reste à privilégier imo))
> 
> donc faudrait changer ça aux quelques endroits où ça apparaît

changé dans le bot mais faudra le changer sur la map anglaise que je sais plus qui a créé pour #2128
